package codigo;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RocaPez
 */

/* Pendientes
Agregar tokens de errores
Buscar como manejar la ñ y otros caracteres con comportamiento inusual
Agregar en tabla tokens 4ta columna del tipo de token ejemplo token 100, tipo de token = Identificador, token 101 tipo token = Numero
Agregar salida exitosa sin errores en textArea
Comprobar tokens del condicional del file.seek()

*/

public class Compilador extends javax.swing.JFrame {

    private ArrayList<Token> tokens;
    private Lexico lexer;
    private Sintactico sintaxis;
    private File archivo;
    private String archivoPath;

    /**
     * Creates new form Compilador
     */
    public Compilador() throws IOException {
        initComponents();
        init();
    btn_compilar.setEnabled(true); // Siempre habilitado
    }

    private void init() throws IOException {
        tokens = new ArrayList<>();

     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_tablaTokens = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTokens = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        paneCodigo = new javax.swing.JTextPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtA_salida = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_abrir = new javax.swing.JButton();
        btn_compilar = new javax.swing.JButton();

        lbl_tablaTokens.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_tablaTokens.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tablaTokens.setText(">_ Consola");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.darkGray);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(java.awt.Color.darkGray);
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jPanel3.setBackground(java.awt.Color.darkGray);
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(java.awt.Color.darkGray);

        tableTokens.setBackground(new java.awt.Color(25, 26, 29));
        tableTokens.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tableTokens.setForeground(new java.awt.Color(255, 255, 255));
        tableTokens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lexema", "Token", "[Línea]"
            }
        ));
        jScrollPane2.setViewportView(tableTokens);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel8.setBackground(java.awt.Color.darkGray);

        jPanel9.setBackground(java.awt.Color.darkGray);

        paneCodigo.setBackground(new java.awt.Color(25, 26, 29));
        paneCodigo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        paneCodigo.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(paneCodigo);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPanel4.add(jPanel3);

        jPanel6.setBackground(java.awt.Color.darkGray);

        jPanel10.setLayout(new java.awt.BorderLayout());

        txtA_salida.setColumns(20);
        txtA_salida.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtA_salida.setRows(5);
        jScrollPane3.setViewportView(txtA_salida);

        jPanel10.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(jPanel6);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(java.awt.Color.darkGray);

        jPanel2.setBackground(java.awt.Color.darkGray);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_abrir.setBackground(new java.awt.Color(153, 153, 153));
        btn_abrir.setText("Abrir archivo");
        btn_abrir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btn_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_abrirActionPerformed(evt);
            }
        });
        jPanel2.add(btn_abrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, 40));

        btn_compilar.setBackground(new java.awt.Color(0, 128, 0));
        btn_compilar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_compilar.setForeground(new java.awt.Color(255, 255, 255));
        btn_compilar.setText("Compilar");
        btn_compilar.setToolTipText("Ejecutar compilación");
        btn_compilar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        btn_compilar.setEnabled(false);
        btn_compilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_compilarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_compilar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 140, 40));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1264, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_compilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_compilarActionPerformed
        txtA_salida.setText("");
        compilar();
    }//GEN-LAST:event_btn_compilarActionPerformed

    private void btn_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_abrirActionPerformed
        // TODO add your handling code here:

        //examinar
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("txt file", "txt");

        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {

            archivo = chooser.getSelectedFile();
            archivoPath = chooser.getSelectedFile().getAbsolutePath();
            try {

                paneCodigo.read(new BufferedReader(new FileReader(archivoPath)), null);
                btn_compilar.setEnabled(true);

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_abrirActionPerformed

 private void compilar() {
    txtA_salida.setText("");
    analizadorLexico();
    llenarTablaTokens();
    
    // Verificar si hay tokens antes del análisis sintáctico
    if (tokens.isEmpty()) {
        txtA_salida.append("Error: El archivo está vacío.\n");
        return;
    }
    
    if(!lexer.errorFound){
        analizadorSintactico();
    } 
}
    private void ReadTxtAreaArchivo() {
        try {
            lexer = new Lexico(archivoPath);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

   private void analizadorLexico() {
    tokens.clear();
    boolean isTempFile = false;
    File tempFile = null;

    try {
        File codigo;
        if (archivoPath != null) {
            codigo = new File(archivoPath);
        } else {
            // Crear un archivo temporal
            tempFile = File.createTempFile("tempCode", ".txt");
            tempFile.deleteOnExit(); // Asegurar que se elimine al salir
            archivoPath = tempFile.getAbsolutePath();
            isTempFile = true;
            // Escribir el contenido del área de texto en el archivo temporal
            FileOutputStream output = new FileOutputStream(tempFile);
            output.write(paneCodigo.getText().getBytes());
            output.close();
            codigo = tempFile;
        }

        // Sobrescribir el archivo con el contenido actual del área de texto
        FileOutputStream output = new FileOutputStream(codigo);
        byte[] bytesText = paneCodigo.getText().getBytes();
        output.write(bytesText);
        output.close();

        lexer = new Lexico(archivoPath);

    } catch (IOException ex) {
        System.out.println("Error al crear archivo temporal... " + ex.getMessage());
        return;
    }

    tokens = lexer.lexico(txtA_salida);

    // Eliminar el archivo temporal si se creó
    if (isTempFile && tempFile != null) {
        tempFile.delete();
        archivoPath = null; // Resetear la ruta del archivo
    }
}
    
    private void analizadorSintactico(){
        sintaxis = new Sintactico();
        sintaxis.cabeza = lexer.cabeza;
        
        sintaxis.sintaxis();

        // Agregar salida sintáctica usando el nuevo getter (antes: sintaxis.resultado)
        txtA_salida.append(sintaxis.getResultado());
        // MOSTRAR CÓDIGO INTERMEDIO
        if (!sintaxis.errorSintactico) {
            mostrarCodigoIntermedio();
            // Mostrar también la versión optimizada producida por GeneradorCodigo
            mostrarCodigoOptimizado();
        }
    }

    private void mostrarCodigoIntermedio() {
        GeneradorCodigo genCodigo = sintaxis.getGeneradorCodigo();
        if (genCodigo != null && !genCodigo.getCodigoIntermedio().isEmpty()) {
            txtA_salida.append("\n=== CÓDIGO INTERMEDIO (NOTACIÓN POLACA) ===\n");
            txtA_salida.append(genCodigo.getCodigoComoString());
        }
    }

    private void mostrarCodigoOptimizado() {
        GeneradorCodigo genCodigo = sintaxis.getGeneradorCodigo();
        if (genCodigo != null) {
            txtA_salida.append("\n\n=== CÓDIGO INTERMEDIO (OPTIMIZADO) ===\n");
            txtA_salida.append(genCodigo.getCodigoOptimizadoComoString());
        }
    }

    private void llenarTablaTokens() {
        DefaultTableModel model = (DefaultTableModel) tableTokens.getModel();

        // Limpiar tabla
        model.setRowCount(0);
 
        tokens.forEach(token -> {
            Object[] data = new Object[]{
                token.getLexema(),
                token.getidToken(),
                "[" + token.getLinea() + "]"
            };
            model.addRow(data);
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Compilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Compilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Compilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Compilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Compilador().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Compilador.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_abrir;
    private javax.swing.JButton btn_compilar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_tablaTokens;
    private javax.swing.JTextPane paneCodigo;
    private javax.swing.JTable tableTokens;
    private javax.swing.JTextArea txtA_salida;
    // End of variables declaration//GEN-END:variables
}
